FROM intel-2018v4-hpc-stack-jedi:ubuntu18

SHELL ["/bin/bash", "-c"]

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends -o=Dpkg::Use-Pty=0 \
        git-flow \
        graphviz && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3-dev \
        python3-pip \
        python3-scipy \
        python3-yaml && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /usr/bin/python && \
    ln -s /usr/bin/python3.6 /usr/bin/python

ENV CMAKE_C_COMPILER=mpiicc \
    CMAKE_CXX_COMPILER=mpiicpc \
    CMAKE_Fortran_COMPILER=mpiifort \
    CMAKE_Platform=linux.intel \
    CMAKE_PREFIX_PATH=/home/builder/opt \
    ESMFMKFILE=/home/builder/opt/lib/esmf.mk \
    NETCDF=/home/builder/opt \
    CMAKE_FLAGS="-DOPENMP=OFF -DPARALLEL_NETCDF=ON -DS2S=ON -DAVX2=OFF" \
    CCPP_SUITES="FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled"

RUN . /etc/profile && \
    export PATH=/home/builder/opt/bin:$PATH && \
    export LD_LIBRARY_PATH=/home/builder/opt/lib:$LD_LIBRARY_PATH && \
    cd /home/builder/opt && git clone https://github.com/ufs-community/ufs-weather-model.git && \
    cd /home/builder/opt/ufs-weather-model && \
    git submodule update --recursive --init && \
    ./build.sh
